package com.pmtool;

import jakarta.transaction.Transactional;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpStatus;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;

record LoginRequest(String username, String password) {}
record PasswordRequest(String oldPassword, String newPassword) {}
record UserInput(String username, String password, String displayName, String roleCode, Long departmentId) {}
record CustomerInput(String name, String level, String status, String contactName, String phone) {}
record ProjectInput(String name, String code, Long customerId, String description, String status, LocalDateTime startDate, LocalDateTime endDate) {}
record TaskInput(Long projectId, String title, String description, Long assigneeId, String status, String priority, BigDecimal estimatedHours, BigDecimal progress, LocalDateTime startDate, LocalDateTime dueDate, Long version) {}
record WorkLogInput(Long taskId, BigDecimal hours, LocalDate workDate, String description, Long version) {}
record BatchTaskStatusInput(List<Long> taskIds, String status) {}

@Service
class PmToolService {
    private final UserRepository users; private final CustomerRepository customers; private final ProjectRepository projects; private final ProjectMemberRepository members; private final MilestoneRepository milestones; private final TaskRepository tasks; private final TaskDependencyRepository dependencies; private final WorkLogRepository logs; private final NotificationRepository notifications; private final OperationLogRepository operationLogs; private final PasswordEncoder encoder; private final JwtService jwt;
    PmToolService(UserRepository users, CustomerRepository customers, ProjectRepository projects, ProjectMemberRepository members, MilestoneRepository milestones, TaskRepository tasks, TaskDependencyRepository dependencies, WorkLogRepository logs, NotificationRepository notifications, OperationLogRepository operationLogs, PasswordEncoder encoder, JwtService jwt) { this.users=users;this.customers=customers;this.projects=projects;this.members=members;this.milestones=milestones;this.tasks=tasks;this.dependencies=dependencies;this.logs=logs;this.notifications=notifications;this.operationLogs=operationLogs;this.encoder=encoder;this.jwt=jwt; }
    CurrentUser current() { Object p=SecurityContextHolder.getContext().getAuthentication().getPrincipal(); if (p instanceof CurrentUser u) return u; throw fail(40100,HttpStatus.UNAUTHORIZED,"未登录"); }
    boolean admin(CurrentUser u){return "ADMIN".equals(u.role());} boolean manager(CurrentUser u){return admin(u)||"PM".equals(u.role());}
    BusinessException fail(int code,HttpStatus s,String message){return new BusinessException(code,s,message);}
    UserAccount user(Long id){return users.findById(id).filter(x->!x.deleted).orElseThrow(()->fail(40400,HttpStatus.NOT_FOUND,"用户不存在"));}
    Project project(Long id){return projects.findById(id).filter(x->!x.deleted).orElseThrow(()->fail(40400,HttpStatus.NOT_FOUND,"项目不存在"));}
    TaskItem task(Long id){return tasks.findById(id).filter(x->!x.deleted).orElseThrow(()->fail(40400,HttpStatus.NOT_FOUND,"任务不存在"));}
    void log(String action,String type,Long id,String detail){operationLogs.save(new OperationLog(current().id(),action,type,id,detail));}
    Map<String,Object> login(LoginRequest req){ UserAccount u=users.findByUsernameAndDeletedFalse(req.username()).orElseThrow(()->fail(40100,HttpStatus.UNAUTHORIZED,"用户名或密码错误")); if(!u.enabled||!encoder.matches(req.password(),u.passwordHash))throw fail(40100,HttpStatus.UNAUTHORIZED,"用户名或密码错误"); logFor(u.id,"LOGIN","USER",u.id,"登录"); return Map.of("token",jwt.create(u),"user",userView(u)); }
    void logFor(Long uid,String action,String type,Long id,String d){ operationLogs.save(new OperationLog(uid,action,type,id,d)); }
    Map<String,Object> me(){return userView(user(current().id()));}
    void changePassword(PasswordRequest req){UserAccount u=user(current().id());if(!encoder.matches(req.oldPassword(),u.passwordHash))throw fail(40001,HttpStatus.BAD_REQUEST,"旧密码错误");if(req.newPassword()==null||req.newPassword().length()<8)throw fail(40001,HttpStatus.BAD_REQUEST,"新密码至少 8 位");u.passwordHash=encoder.encode(req.newPassword());users.save(u);log("UPDATE","USER",u.id,"修改密码");}
    List<Map<String,Object>> allUsers(){return users.findByDeletedFalse(org.springframework.data.domain.Pageable.unpaged()).stream().map(this::userView).toList();}
    @Transactional UserAccount createUser(UserInput i){requireAdmin();if(users.findByUsernameAndDeletedFalse(i.username()).isPresent())throw fail(40900,HttpStatus.CONFLICT,"用户名已存在");UserAccount u=new UserAccount(i.username(),encoder.encode(i.password()),i.displayName(),Optional.ofNullable(i.roleCode()).orElse("MEMBER"));u.departmentId=i.departmentId();users.save(u);log("CREATE","USER",u.id,u.username);return u;}
    @Transactional Customer saveCustomer(CustomerInput i,Long id){requireManager();Customer c=id==null?new Customer():customer(id);c.name=i.name();c.level=Optional.ofNullable(i.level()).orElse("normal");c.status=Optional.ofNullable(i.status()).orElse("active");c.contactName=i.contactName();c.phone=i.phone();customers.save(c);log(id==null?"CREATE":"UPDATE","CUSTOMER",c.id,c.name);return c;}
    Customer customer(Long id){return customers.findById(id).filter(x->!x.deleted).orElseThrow(()->fail(40400,HttpStatus.NOT_FOUND,"客户不存在"));}
    @Transactional Project saveProject(ProjectInput i,Long id){CurrentUser u=current();if(!manager(u))throw fail(40300,HttpStatus.FORBIDDEN,"无项目管理权限");Project p=id==null?new Project():project(id);if(id!=null)ensureProjectManager(p,u);p.name=i.name();p.code=i.code();p.customerId=i.customerId();p.description=i.description();p.status=Optional.ofNullable(i.status()).orElse("planning");p.startDate=i.startDate();p.endDate=i.endDate();if(id==null){p.managerId=u.id();p.progress=BigDecimal.ZERO;}projects.save(p);if(id==null)members.save(new ProjectMember(p.id,u.id(),"PM"));log(id==null?"CREATE":"UPDATE","PROJECT",p.id,p.name);return p;}
    void ensureProjectAccess(Project p,CurrentUser u){if(admin(u)||Objects.equals(p.managerId,u.id())||members.existsByIdProjectIdAndIdUserId(p.id,u.id()))return;throw fail(40300,HttpStatus.FORBIDDEN,"无项目访问权限");}
    void ensureProjectManager(Project p,CurrentUser u){if(admin(u)||Objects.equals(p.managerId,u.id()))return;throw fail(40300,HttpStatus.FORBIDDEN,"仅项目经理可管理项目");}
    List<Project> visibleProjects(){CurrentUser u=current();return projects.findByDeletedFalse(org.springframework.data.domain.Pageable.unpaged()).getContent().stream().filter(p->admin(u)||Objects.equals(p.managerId,u.id())||members.existsByIdProjectIdAndIdUserId(p.id,u.id())).toList();}
    List<TaskItem> visibleTasks(){Set<Long> ids=visibleProjects().stream().map(p->p.id).collect(java.util.stream.Collectors.toSet());return tasks.findByDeletedFalse(org.springframework.data.domain.Pageable.unpaged()).getContent().stream().filter(t->ids.contains(t.projectId)).toList();}
    List<WorkLog> visibleWorkLogs(){CurrentUser u=current();if(admin(u))return logs.findByDeletedFalse(org.springframework.data.domain.Pageable.unpaged()).getContent();Map<Long,TaskItem> taskMap=new HashMap<>();tasks.findByDeletedFalse(org.springframework.data.domain.Pageable.unpaged()).forEach(t->taskMap.put(t.id,t));return logs.findByDeletedFalse(org.springframework.data.domain.Pageable.unpaged()).getContent().stream().filter(w->{if(w.userId.equals(u.id()))return true;TaskItem t=taskMap.get(w.taskId);return t!=null&&Objects.equals(project(t.projectId).managerId,u.id());}).toList();}
    @Transactional void addMember(Long projectId,Long userId,String role){Project p=project(projectId);ensureProjectManager(p,current());user(userId);members.save(new ProjectMember(projectId,userId,Optional.ofNullable(role).orElse("MEMBER")));log("UPDATE","PROJECT",projectId,"添加成员");}
    @Transactional TaskItem saveTask(TaskInput i,Long id){Project p=project(i.projectId());CurrentUser u=current();ensureProjectAccess(p,u);TaskItem t=id==null?new TaskItem():task(id);if(id!=null&&i.version()!=null&&!Objects.equals(i.version(),t.version))throw fail(40900,HttpStatus.CONFLICT,"任务已被其他用户更新");if(id!=null&&!Objects.equals(t.projectId,i.projectId()))throw fail(40001,HttpStatus.BAD_REQUEST,"任务不可跨项目移动");if(!manager(u)&&id!=null&&!Objects.equals(t.assigneeId,u.id()))throw fail(40300,HttpStatus.FORBIDDEN,"成员只能更新自己的任务");if(!manager(u)&&id==null)throw fail(40300,HttpStatus.FORBIDDEN,"成员不能创建任务");if(manager(u)){t.projectId=i.projectId();t.title=i.title();t.description=i.description();t.assigneeId=i.assigneeId();t.status=Optional.ofNullable(i.status()).orElse("todo");t.priority=Optional.ofNullable(i.priority()).orElse("medium");t.estimatedHours=i.estimatedHours();t.startDate=i.startDate();t.dueDate=i.dueDate();}else{t.status=Optional.ofNullable(i.status()).orElse(t.status);}t.progress=Optional.ofNullable(i.progress()).orElse(t.progress);if(id==null)t.sortOrder=tasks.findByProjectIdAndDeletedFalseOrderBySortOrderAsc(p.id).size();tasks.save(t);recalculateProgress(p);if(manager(u)&&t.assigneeId!=null&&!Objects.equals(t.assigneeId,u.id()))notifications.save(new NotificationItem(t.assigneeId,"任务已指派",t.title,"task_assigned"));log(id==null?"CREATE":"UPDATE","TASK",t.id,t.title);return t;}
    @Transactional void updateTaskStatus(Long id,String status,Long version){TaskItem t=task(id);Project p=project(t.projectId);CurrentUser u=current();ensureProjectAccess(p,u);if(!manager(u)&&!Objects.equals(t.assigneeId,u.id()))throw fail(40300,HttpStatus.FORBIDDEN,"只能更新自己的任务");if(version!=null&&!Objects.equals(version,t.version))throw fail(40900,HttpStatus.CONFLICT,"任务已被更新");t.status=status;t.progress="done".equals(status)?BigDecimal.valueOf(100):t.progress;tasks.save(t);recalculateProgress(p);if(p.managerId!=null)notifications.save(new NotificationItem(p.managerId,"任务状态更新",t.title+" → "+status,"task_status"));log("UPDATE","TASK",t.id,"更新状态");}
    @Transactional void reorder(Long projectId,List<Long> ids){Project p=project(projectId);ensureProjectManager(p,current());Map<Long,TaskItem> map=new HashMap<>();tasks.findByProjectIdAndDeletedFalse(projectId).forEach(t->map.put(t.id,t));for(int n=0;n<ids.size();n++){TaskItem t=map.get(ids.get(n));if(t==null)throw fail(40001,HttpStatus.BAD_REQUEST,"任务不属于项目");t.sortOrder=n;tasks.save(t);}log("UPDATE","PROJECT",projectId,"任务重排序");}
    @Transactional void batchUpdateStatus(BatchTaskStatusInput input){if(input.taskIds()==null||input.taskIds().isEmpty()||input.status()==null||input.status().isBlank())throw fail(40001,HttpStatus.BAD_REQUEST,"任务和状态不能为空");for(Long id:input.taskIds())updateTaskStatus(id,input.status(),null);}
    @Transactional void addDependency(Long taskId,Long dependsOnTaskId){TaskItem task=task(taskId),predecessor=task(dependsOnTaskId);if(Objects.equals(taskId,dependsOnTaskId))throw fail(40001,HttpStatus.BAD_REQUEST,"任务不能依赖自身");if(!Objects.equals(task.projectId,predecessor.projectId))throw fail(40001,HttpStatus.BAD_REQUEST,"依赖任务必须属于同一项目");ensureProjectManager(project(task.projectId),current());TaskDependencyId id=new TaskDependencyId(taskId,dependsOnTaskId);if(dependencies.existsById(id))return;if(hasDependencyPath(dependsOnTaskId,taskId,new HashSet<>()))throw fail(40001,HttpStatus.BAD_REQUEST,"任务依赖会形成循环");dependencies.save(new TaskDependency(taskId,dependsOnTaskId));log("CREATE","TASK_DEPENDENCY",taskId,"依赖任务 "+dependsOnTaskId);}
    @Transactional void removeDependency(Long taskId,Long dependsOnTaskId){TaskItem task=task(taskId);ensureProjectManager(project(task.projectId),current());TaskDependencyId id=new TaskDependencyId(taskId,dependsOnTaskId);if(!dependencies.existsById(id))throw fail(40400,HttpStatus.NOT_FOUND,"任务依赖不存在");dependencies.deleteById(id);log("DELETE","TASK_DEPENDENCY",taskId,"移除依赖任务 "+dependsOnTaskId);}
    List<Long> dependenciesOf(Long taskId){TaskItem task=task(taskId);ensureProjectAccess(project(task.projectId),current());return dependencies.findByIdTaskId(taskId).stream().map(x->x.id.dependsOnTaskId).toList();}
    List<Map<String,Object>> gantt(Long projectId){Project project=project(projectId);ensureProjectAccess(project,current());Map<Long,List<Long>> depends=new HashMap<>();for(TaskItem task:tasks.findByProjectIdAndDeletedFalseOrderBySortOrderAsc(projectId))depends.put(task.id,dependencies.findByIdTaskId(task.id).stream().map(x->x.id.dependsOnTaskId).toList());return tasks.findByProjectIdAndDeletedFalseOrderBySortOrderAsc(projectId).stream().map(t->Map.<String,Object>of("id",t.id,"title",t.title,"startDate",Optional.ofNullable(t.startDate).map(Object::toString).orElse(""),"dueDate",Optional.ofNullable(t.dueDate).map(Object::toString).orElse(""),"progress",t.progress,"status",t.status,"dependsOn",depends.get(t.id))).toList();}
    private boolean hasDependencyPath(Long from,Long target,Set<Long> visited){if(Objects.equals(from,target))return true;if(!visited.add(from))return false;return dependencies.findByIdTaskId(from).stream().anyMatch(d->hasDependencyPath(d.id.dependsOnTaskId,target,visited));}
    void recalculateProgress(Project p){List<TaskItem> ts=tasks.findByProjectIdAndDeletedFalse(p.id);if(ts.isEmpty()){p.progress=BigDecimal.ZERO;}else{BigDecimal total=BigDecimal.ZERO,weighted=BigDecimal.ZERO;for(TaskItem t:ts){BigDecimal w=t.estimatedHours==null?BigDecimal.ONE:t.estimatedHours;total=total.add(w);weighted=weighted.add(t.progress.multiply(w));}p.progress=weighted.divide(total,2,RoundingMode.HALF_UP);}projects.save(p);}
    @Transactional WorkLog saveWorkLog(WorkLogInput i,Long id){TaskItem t=task(i.taskId());Project p=project(t.projectId);CurrentUser u=current();ensureProjectAccess(p,u);if(i.hours()==null||i.hours().signum()<=0||i.workDate()==null)throw fail(40001,HttpStatus.BAD_REQUEST,"工时和日期必须有效");if(id==null){WorkLog w=new WorkLog();w.taskId=i.taskId();w.userId=u.id();w.hours=i.hours();w.workDate=i.workDate();w.description=i.description();logs.save(w);log("CREATE","WORK_LOG",w.id,"提交工时");return w;}WorkLog w=logs.findById(id).filter(x->!x.deleted).orElseThrow(()->fail(40400,HttpStatus.NOT_FOUND,"工时不存在"));if(!Objects.equals(w.taskId,i.taskId()))throw fail(40001,HttpStatus.BAD_REQUEST,"工时记录不可变更任务");if(i.version()!=null&&!Objects.equals(i.version(),w.version))throw fail(40900,HttpStatus.CONFLICT,"工时已被其他用户更新");if(!manager(u)&&!Objects.equals(w.userId,u.id()))throw fail(40300,HttpStatus.FORBIDDEN,"无工时修改权限");if("approved".equals(w.status)&&!manager(u))throw fail(40300,HttpStatus.FORBIDDEN,"已审批工时仅管理员或项目经理可修改");w.hours=i.hours();w.workDate=i.workDate();w.description=i.description();w.status="pending";w.reviewerId=null;w.reviewComment=null;logs.save(w);log("UPDATE","WORK_LOG",w.id,"修改后重新审批");return w;}
    @Transactional void reviewWorkLog(Long id,boolean approved,String comment){requireManager();WorkLog w=logs.findById(id).filter(x->!x.deleted).orElseThrow(()->fail(40400,HttpStatus.NOT_FOUND,"工时不存在"));w.status=approved?"approved":"rejected";w.reviewerId=current().id();w.reviewComment=comment;logs.save(w);notifications.save(new NotificationItem(w.userId,approved?"工时已审批":"工时已驳回",Optional.ofNullable(comment).orElse(""),"worklog"));log("REVIEW","WORK_LOG",w.id,w.status);}
    Map<String,Object> dashboard(){List<Project> ps=visibleProjects();List<TaskItem> ts=visibleTasks();long done=ts.stream().filter(x->"done".equals(x.status)).count();return Map.of("projectTotal",ps.size(),"taskTotal",ts.size(),"taskDone",done,"taskCompletion",ts.isEmpty()?0:Math.round(done*100.0/ts.size()),"recentProjects",ps.stream().sorted(Comparator.comparing(x->x.updatedAt,Comparator.reverseOrder())).limit(5).map(this::projectView).toList());}
    void requireAdmin(){if(!admin(current()))throw fail(40300,HttpStatus.FORBIDDEN,"仅管理员可操作");}
    void requireManager(){if(!manager(current()))throw fail(40300,HttpStatus.FORBIDDEN,"仅管理员或项目经理可操作");}
    Map<String,Object> userView(UserAccount u){return Map.of("id",u.id,"username",u.username,"displayName",u.displayName,"roleCode",u.roleCode,"departmentId",Optional.ofNullable(u.departmentId).orElse(0L),"enabled",u.enabled);}
    Map<String,Object> projectView(Project p){return Map.of("id",p.id,"name",p.name,"code",p.code,"managerId",p.managerId,"customerId",Optional.ofNullable(p.customerId).orElse(0L),"status",p.status,"progress",p.progress,"version",p.version==null?0:p.version);}
    @Scheduled(cron="0 30 2 * * *") void cleanLogs(){operationLogs.deleteByCreatedAtBefore(LocalDateTime.now().minusDays(180));}
    @Scheduled(cron="0 0 9 * * *") @Transactional void notifyUpcomingMilestones(){LocalDate today=LocalDate.now();Set<LocalDate> targets=Set.of(today.plusDays(1),today.plusDays(3),today.plusDays(7));for(Milestone milestone:milestones.findByDueDateBetweenAndDeletedFalse(today.atStartOfDay(),today.plusDays(8).atStartOfDay())){if(milestone.dueDate==null||!targets.contains(milestone.dueDate.toLocalDate()))continue;Project project=projects.findById(milestone.projectId).orElse(null);if(project==null||project.deleted)continue;String title="里程碑临期："+milestone.name+"（"+milestone.dueDate.toLocalDate()+"）";Set<Long> receivers=new HashSet<>();receivers.add(project.managerId);members.findByIdProjectId(project.id).forEach(m->receivers.add(m.id.userId));for(Long userId:receivers)if(!notifications.existsByUserIdAndTitle(userId,title))notifications.save(new NotificationItem(userId,title,"项目「"+project.name+"」的里程碑即将到期","milestone_due"));}}
    @Bean ApplicationRunner seed(@org.springframework.beans.factory.annotation.Value("${pmtool.admin.username}") String username,@org.springframework.beans.factory.annotation.Value("${pmtool.admin.password}") String password){return a->{if(users.findByUsernameAndDeletedFalse(username).isEmpty())users.save(new UserAccount(username,encoder.encode(password),"系统管理员","ADMIN"));};}
}
