CREATE TABLE departments (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  parent_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0'
);
CREATE TABLE roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NULL
);
CREATE TABLE permissions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(80) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL
);
CREATE TABLE users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  role_code VARCHAR(40) NOT NULL,
  department_id BIGINT NULL,
  enabled BIT NOT NULL DEFAULT b'1',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0'
);
CREATE TABLE user_roles (user_id BIGINT NOT NULL, role_id BIGINT NOT NULL, PRIMARY KEY (user_id, role_id));
CREATE TABLE role_permissions (role_id BIGINT NOT NULL, permission_id BIGINT NOT NULL, PRIMARY KEY (role_id, permission_id));
CREATE TABLE customers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  level VARCHAR(20) NOT NULL DEFAULT 'normal',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  contact_name VARCHAR(100) NULL,
  phone VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0'
);
CREATE TABLE projects (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  customer_id BIGINT NULL,
  manager_id BIGINT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'planning',
  description TEXT NULL,
  start_date DATETIME NULL,
  end_date DATETIME NULL,
  progress DECIMAL(5,2) NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0',
  INDEX idx_projects_manager (manager_id, deleted)
);
CREATE TABLE project_members (project_id BIGINT NOT NULL, user_id BIGINT NOT NULL, role_code VARCHAR(40) NOT NULL DEFAULT 'MEMBER', PRIMARY KEY (project_id, user_id));
CREATE TABLE milestones (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT NOT NULL,
  name VARCHAR(150) NOT NULL,
  due_date DATETIME NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  deleted BIT NOT NULL DEFAULT b'0'
);
CREATE TABLE project_tasks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NULL,
  assignee_id BIGINT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'todo',
  priority VARCHAR(20) NOT NULL DEFAULT 'medium',
  estimated_hours DECIMAL(10,2) NULL,
  progress DECIMAL(5,2) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  start_date DATETIME NULL,
  due_date DATETIME NULL,
  version BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0',
  INDEX idx_tasks_project (project_id, status, deleted),
  INDEX idx_tasks_assignee (assignee_id, status, deleted)
);
CREATE TABLE task_dependencies (task_id BIGINT NOT NULL, depends_on_task_id BIGINT NOT NULL, PRIMARY KEY (task_id, depends_on_task_id));
CREATE TABLE work_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  hours DECIMAL(10,2) NOT NULL,
  work_date DATE NOT NULL,
  description VARCHAR(500) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  reviewer_id BIGINT NULL,
  review_comment VARCHAR(500) NULL,
  version BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0'
);
CREATE TABLE attachments (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  target_type VARCHAR(30) NOT NULL,
  target_id BIGINT NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  object_key VARCHAR(255) NOT NULL,
  content_type VARCHAR(100) NULL,
  size_bytes BIGINT NOT NULL,
  uploader_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0'
);
CREATE TABLE project_documents (id BIGINT PRIMARY KEY AUTO_INCREMENT, project_id BIGINT NOT NULL, title VARCHAR(150) NOT NULL, content TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted BIT NOT NULL DEFAULT b'0');
CREATE TABLE project_risks (id BIGINT PRIMARY KEY AUTO_INCREMENT, project_id BIGINT NOT NULL, title VARCHAR(150) NOT NULL, level VARCHAR(20) NOT NULL DEFAULT 'medium', status VARCHAR(30) NOT NULL DEFAULT 'open', owner_id BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted BIT NOT NULL DEFAULT b'0');
CREATE TABLE notifications (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  title VARCHAR(150) NOT NULL,
  content VARCHAR(500) NOT NULL,
  type VARCHAR(30) NOT NULL,
  is_read BIT NOT NULL DEFAULT b'0',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_notifications_user (user_id, is_read, created_at)
);
CREATE TABLE operation_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NULL,
  action VARCHAR(50) NOT NULL,
  resource_type VARCHAR(50) NOT NULL,
  resource_id BIGINT NULL,
  detail VARCHAR(500) NULL,
  trace_id VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_logs_created (created_at)
);
